#!/bin/bash

#git remote -v
#git remote add main ssh://172.29.0.92/8916/platform/vendor/qcom/msm8916_64
# git push main HEAD:refs/for/dev/msm8916/asus/a601
#替换ip法
echo "========================================="
echo " git_push.sh Script V3.0"
echo "========================================="

up_remote=172.29.0.92
up_remote_ip=172.29.0.92

if [ "$#" -eq 0 ];then
	git push
	exit 1
fi

isRepository=false
command="git push"
index=1
for arg in "$@"
do 
	echo "Arg #$index : 	$arg"

	let index+=1
	if [ -z "$(echo $arg | grep "-")" ] && [ $isRepository == false ]; then
		isRepository=true
		if [ -n "$(git remote show | grep $arg)" ];then

		#projectname_pattern="remote.$arg.projectname"
		#echo "projectname_pattern:	$projectname_pattern"
		#remote_name=$(git config --list | awk -F "=" '{if($1=="'$projectname_pattern'") print $2}')
		local_remote_url=$(git config --list | grep "$arg.url")
		local_remote_url=$(echo ${local_remote_url#*=})
		#path=$(echo ${local_remote_url#*//*/})

		if [[ $local_remote_url =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] ; then
				local_ip=$(echo "$BASH_REMATCH")
			else
				echo ip_fail ; 
		fi
		remote_url=$(echo ${local_remote_url/$local_ip/$up_remote_ip})
		#echo "local_ip:	$local_ip"
		#echo "path:		$path"
		#echo "up_remote_ip:	$up_remote_ip"
		#echo "remote_name:	$remote_name"
		#remote_url="ssh://$up_remote/$remote_name"

		command_add=$command
		command="$command $remote_url"
		else
			echo "fatal: can not found the remote repository '$arg'"
			exit 1;
		fi
	else
		command="$command $arg"
	fi

done

#echo "command_add:	$command_add"
#echo "remote_url:	$remote_url"
#echo "arg:		$arg"
#echo "exe command: 	$command"

#remote_url=ssh://$ip/$path
command="git push  $remote_url $arg"
echo "exe command: 	$command"
echo ""
$command
#git push main $arg

exit 0





