#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-y += fts_ts.o 
fts_ts-y += focaltech_core.o focaltech_ctl.o focaltech_ex_fun.o focaltech_flash.o Config_FT6X36.o DetailThreshold.o Global.o ini.o Test_FT6X36.o test_lib.o
