#
# Makefile for the fingerprint sensor drivers select.
#

obj-$(CONFIG_FINGERPRINT_GOODIX316M)	+= goodix/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF5216)	+= goodix_5216/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += goodixgf3208/


