#
# Makefile for the fingerprint sensor drivers select.
#

#obj-$(CONFIG_FINGERPRINT_SYNAPTICS)	+= synaptics/

obj-$(CONFIG_FINGERPRINT_GOODIX316M)	+= goodix316m/

obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208)	+= goodixgf3208/


