#
# Makefile for the RockChip PreIsp device drivers.
#
EXTRA_CFLAGS += -Wno-unused-variable
EXTRA_CFLAGS += -Wno-unused-label
EXTRA_CFLAGS += -Wno-unused-value
EXTRA_CFLAGS += -Wno-unused-parameter
EXTRA_CFLAGS += -Wno-unused-function
EXTRA_CFLAGS += -Wno-unused
rkpreisp-objs := spi-rkpreisp.o isp-fw.o spi2apb.o msg-queue.o ap-i2c.o
obj-y += rkpreisp.o
